### ISSUE TITLE
Ambient global namespace not found

### ISSUE THREAD

**Issue by kuon** [brunch/typescript-brunch#18]
I am trying to use the youtube definition file https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/youtube/youtube.d.ts

This file is referenced from my `app.ts` file with `/// <reference path="youtube.d.ts" />`.

I can compile my `app.ts` file with `tsc -m commonjs`, but with brunch, I got:
`Error 2503: Cannot find namespace 'YT'. (Line: 104, Col: 28)`

If I copy the content of the `youtube.d.ts` file in my `app.ts` brunch can then compile it.

Any idea?

**Comment by baptistedonaux** [comment]
Hi @kuon,

Sorry the waiting. If you have always the problem, I can take few minutes to check that this issue is not thrown by **brunch-typescript**.

**Comment by CarsonF** [comment]
I'm having the same problem. But only with some of the uses which is weird.

**Comment by CarsonF** [comment]
Just ignoring the error seemed to work for me.
```js
plugins: {
  brunchTypescript: {
    ignoreErrors: [
      2503 // Cannot find namespace {0}
    ]
  }
}
```

**Comment by colinbate** [comment]
Sorry, I should have chimed in earlier. This plugin runs TypeScript in a single file isolation mode. That means that it looks at each file without any outside context. It makes it faster, but it is also a lot less "intelligent". When we started surfacing errors, it was obvious that many of the errors were because of this mode. Finding outside namespaces is obviously one such error. We can add it to the list which are ignored by default which will help in this case.

I had started looking into an option to run the full typescript language server as part of compilation (perhaps when doing a regular build without watching). I didn't get very far with that.

If you are using this plugin, I recommend adding `tsc --noEmit` as part of your `npm test` script. That should catch any proper TS errors. Your editor may also be catching them, but it is nice to have something you can run in your CI tool.

**Comment by CarsonF** [comment]
Ah that's why `tsc` catches more errors than this does. Thanks for `--noEmit` hint.

**Comment by baptistedonaux** [comment]
@colinbate Can you improve brunch-typescript in any way ?

**Comment by kuon** [comment]
@baptistedonaux I think it would require using the typescript service.

When I was using browserify, I was using https://github.com/TypeStrong/tsify which uses the typescript services.
