### ISSUE TITLE
Error while loading the tsconfig.json should not be hidden

### ISSUE THREAD

**Issue by galenus** [brunch/typescript-brunch#29]
Steps to reproduce:
1) Create any simple project with .tsx file containing JSX tags and tsconfig.json setting "jsx":"react"
2) Add a comment inside tsconfig.json
3) Try to build the project

Result: compilation will fail with "Unrecognized token" error.
Expected: compilation should fail with an error pointing to the real cause.

**Comment by paulmedynski** [comment]
I think the underlying problem here is that `typescript-brunch` uses Node's `require()` function to read `tsconfig.json`, which doesn't support JavaScript comments.  TypeScript does define `tsconfig.json` to allow JavaScript comments, so `typescript-brunch` should as well.  We can either strip the comments by hand and use `JSON.parse()`, or use one of the many NPM modules that do this for you.

Either way, yes, I agree that failing to load a `tsconfig.json` (when it exists) should emit an error or stop the build.

**Comment by paulmedynski** [comment]
@paulmillr (and others) - Before I start working on this, is it taboo to add a dependency to do this comment stripping, or should I write something sufficient by hand?  I'm fine with either, but I'd rather the former if it's ok with the maintainers.

**Comment by paulmillr** [comment]
by hand is better
